server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://111.230.223.115/eshop?useSSL=false
    username: eshop
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
#  type-aliases-package: cn.edu.jxufe.shopping.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cn.edu.jxufe.shopping.entity: debug
    cn.edu.jxufe.shopping.mapper: debug
    cn.edu.jxufe.shopping.controller: debug
